name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:

    - name: name

    - name: Build
      run: |
        git clone --branch fec0e30b17 git@github.com:oxi1224/keydrop-website.git
